// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using TeamFlow.Infrastructure.Persistence;

#nullable disable

namespace TeamFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TeamFlowDbContext))]
    partial class TeamFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "attachment_owner", new[] { "task", "message", "project", "comment" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "channel_type", new[] { "public", "private", "direct" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "delivery_channel", new[] { "email", "push", "in_app" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "notification_kind", new[] { "mention", "assignment", "comment", "status", "invite", "system" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "priority_level", new[] { "low", "medium", "high", "critical" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "project_member_role", new[] { "lead", "contributor", "viewer" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "project_status", new[] { "planning", "active", "on_hold", "archived", "completed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "task_column", new[] { "backlog", "todo", "in_progress", "review", "done" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "workspace_role", new[] { "owner", "admin", "member", "guest" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamFlow.Domain.Activity.ActivityEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_kind");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("verb");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_activity_events");

                    b.HasIndex("ActorId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_activity_events_actor_id_created_at");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_activity_events_project_id_created_at");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_activity_events_workspace_id_created_at");

                    b.ToTable("activity_events", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Attachments.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("OwnerKind")
                        .HasColumnType("attachment_owner")
                        .HasColumnName("owner_kind");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("OwnerKind", "OwnerId")
                        .HasDatabaseName("ix_attachments_owner_kind_owner_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Discussions.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("Topic")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("topic");

                    b.Property<int>("Type")
                        .HasColumnType("channel_type")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_workspace_id_name");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Discussions.ChannelMember", b =>
                {
                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_muted");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset>("LastReadAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_read_at");

                    b.HasKey("ChannelId", "UserId")
                        .HasName("pk_channel_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_channel_members_user_id");

                    b.ToTable("channel_members", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Discussions.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("edited_at");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<NpgsqlTsVector>("search_tsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_tsv")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(body, ''))", true);

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("search_tsv")
                        .HasDatabaseName("ix_messages_search_tsv");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("search_tsv"), "gin");

                    b.HasIndex("ChannelId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_messages_channel_id_created_at")
                        .HasFilter("deleted_at IS NULL AND parent_id IS NULL");

                    b.HasIndex("ParentId", "CreatedAt")
                        .HasDatabaseName("ix_messages_parent_id_created_at")
                        .HasFilter("parent_id IS NOT NULL");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Discussions.MessageMention", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("MessageId", "UserId")
                        .HasName("pk_message_mentions");

                    b.ToTable("message_mentions", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Discussions.MessageReaction", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Emoji")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("emoji");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.HasKey("MessageId", "UserId", "Emoji")
                        .HasName("pk_message_reactions");

                    b.ToTable("message_reactions", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("Kind")
                        .HasColumnType("notification_kind")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKind")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_kind");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_notifications_unread")
                        .HasFilter("read_at IS NULL");

                    b.HasIndex("RecipientId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_notifications_recipient_id_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Notifications.NotificationPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<int>("Kind")
                        .HasColumnType("notification_kind")
                        .HasColumnName("kind");

                    b.Property<int>("Channel")
                        .HasColumnType("delivery_channel")
                        .HasColumnName("channel");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.HasKey("UserId", "WorkspaceId", "Kind", "Channel")
                        .HasName("pk_notification_preferences");

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NextTaskNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("next_task_number");

                    b.Property<int>("Priority")
                        .HasColumnType("priority_level")
                        .HasColumnName("priority");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("project_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("WorkspaceId", "DueDate")
                        .HasDatabaseName("ix_projects_workspace_id_due_date");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_workspace_id_key");

                    b.HasIndex("WorkspaceId", "Status")
                        .HasDatabaseName("ix_projects_workspace_id_status");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Projects.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("added_at");

                    b.Property<int>("Role")
                        .HasColumnType("project_member_role")
                        .HasColumnName("role");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_members_user_id");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Projects.ProjectTag", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("ProjectId", "TagId")
                        .HasName("pk_project_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_project_tags_tag_id");

                    b.ToTable("project_tags", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Tasks.TaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("edited_at");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_task_comments");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_task_comments_parent_id");

                    b.HasIndex("TaskId", "CreatedAt")
                        .HasDatabaseName("ix_task_comments_task_id_created_at");

                    b.ToTable("task_comments", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Tasks.TaskDependency", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("DependsOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("depends_on_id");

                    b.HasKey("TaskId", "DependsOnId")
                        .HasName("pk_task_dependencies");

                    b.HasIndex("DependsOnId")
                        .HasDatabaseName("ix_task_dependencies_depends_on_id");

                    b.ToTable("task_dependencies", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_dependencies_no_self", "task_id <> depends_on_id");
                        });
                });

            modelBuilder.Entity("TeamFlow.Domain.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<int>("Column")
                        .HasColumnType("task_column")
                        .HasColumnName("column");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal?>("EstimateHours")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("estimate_hours");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<decimal>("Position")
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("position");

                    b.Property<int>("Priority")
                        .HasColumnType("priority_level")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<NpgsqlTsVector>("search_tsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_tsv")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'B')", true);

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_tasks_assignee_open")
                        .HasFilter("deleted_at IS NULL AND \"column\" <> 'done'");

                    b.HasIndex("search_tsv")
                        .HasDatabaseName("ix_tasks_search_tsv");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("search_tsv"), "gin");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_tasks_project_id_number");

                    b.HasIndex("WorkspaceId", "DueDate")
                        .HasDatabaseName("ix_tasks_workspace_id_due_date")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ProjectId", "Column", "Position")
                        .HasDatabaseName("ix_tasks_board")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Tasks.TaskTag", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("TaskId", "TagId")
                        .HasName("pk_task_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_task_tags_tag_id");

                    b.ToTable("task_tags", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Tasks.TaskWatcher", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TaskId", "UserId")
                        .HasName("pk_task_watchers");

                    b.ToTable("task_watchers", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Workspaces.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_workspace_id_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_workspaces_owner_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_workspaces_slug");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Workspaces.WorkspaceInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<int>("Role")
                        .HasColumnType("workspace_role")
                        .HasColumnName("role");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_invites");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_invites_token_hash");

                    b.HasIndex("WorkspaceId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_invites_workspace_id_email");

                    b.ToTable("workspace_invites", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Workspaces.WorkspaceMember", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at");

                    b.Property<int>("Role")
                        .HasColumnType("workspace_role")
                        .HasColumnName("role");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("WorkspaceId", "UserId")
                        .HasName("pk_workspace_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workspace_members_user_id");

                    b.ToTable("workspace_members", (string)null);
                });

            modelBuilder.Entity("TeamFlow.Domain.Discussions.ChannelMember", b =>
                {
                    b.HasOne("TeamFlow.Domain.Discussions.Channel", null)
                        .WithMany("Members")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_members_channels_channel_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Discussions.Message", b =>
                {
                    b.HasOne("TeamFlow.Domain.Discussions.Message", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_messages_messages_parent_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Discussions.MessageMention", b =>
                {
                    b.HasOne("TeamFlow.Domain.Discussions.Message", null)
                        .WithMany("Mentions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_mentions_messages_message_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Discussions.MessageReaction", b =>
                {
                    b.HasOne("TeamFlow.Domain.Discussions.Message", null)
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_reactions_messages_message_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Projects.Project", b =>
                {
                    b.OwnsOne("TeamFlow.Domain.Projects.Money", "Budget", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("budget_cents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("budget_currency");

                            b1.HasKey("ProjectId");

                            b1.ToTable("projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_projects_projects_id");
                        });

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("TeamFlow.Domain.Projects.ProjectMember", b =>
                {
                    b.HasOne("TeamFlow.Domain.Projects.Project", null)
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Projects.ProjectTag", b =>
                {
                    b.HasOne("TeamFlow.Domain.Projects.Project", null)
                        .WithMany("Tags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_tags_projects_project_id");

                    b.HasOne("TeamFlow.Domain.Workspaces.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_tags_tags_tag_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Tasks.TaskComment", b =>
                {
                    b.HasOne("TeamFlow.Domain.Tasks.TaskComment", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_task_comments_task_comments_parent_id");

                    b.HasOne("TeamFlow.Domain.Tasks.TaskItem", null)
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_comments_tasks_task_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Tasks.TaskDependency", b =>
                {
                    b.HasOne("TeamFlow.Domain.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("DependsOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_dependencies_tasks_depends_on_id");

                    b.HasOne("TeamFlow.Domain.Tasks.TaskItem", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_dependencies_tasks_task_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Tasks.TaskItem", b =>
                {
                    b.HasOne("TeamFlow.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_projects_project_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Tasks.TaskTag", b =>
                {
                    b.HasOne("TeamFlow.Domain.Workspaces.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_tags_tags_tag_id");

                    b.HasOne("TeamFlow.Domain.Tasks.TaskItem", null)
                        .WithMany("Tags")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_tags_tasks_task_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Tasks.TaskWatcher", b =>
                {
                    b.HasOne("TeamFlow.Domain.Tasks.TaskItem", null)
                        .WithMany("Watchers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_watchers_tasks_task_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Workspaces.Tag", b =>
                {
                    b.HasOne("TeamFlow.Domain.Workspaces.Workspace", null)
                        .WithMany("Tags")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_workspaces_workspace_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Workspaces.WorkspaceInvite", b =>
                {
                    b.HasOne("TeamFlow.Domain.Workspaces.Workspace", null)
                        .WithMany("Invites")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_invites_workspaces_workspace_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Workspaces.WorkspaceMember", b =>
                {
                    b.HasOne("TeamFlow.Domain.Workspaces.Workspace", null)
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");
                });

            modelBuilder.Entity("TeamFlow.Domain.Discussions.Channel", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TeamFlow.Domain.Discussions.Message", b =>
                {
                    b.Navigation("Mentions");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("TeamFlow.Domain.Projects.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("TeamFlow.Domain.Tasks.TaskItem", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Dependencies");

                    b.Navigation("Tags");

                    b.Navigation("Watchers");
                });

            modelBuilder.Entity("TeamFlow.Domain.Workspaces.Workspace", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Members");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
